/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#23005c",
        "tertiary": "#ffb783",
        "primary-fixed": "#e1e0ff",
        "surface-container-lowest": "#0e0e14",
        "primary-fixed-dim": "#c0c1ff",
        "on-secondary-container": "#c4abff",
        "surface-dim": "#13131a",
        "surface-container-highest": "#34343c",
        "on-surface-variant": "#c7c4d7",
        "on-secondary-fixed-variant": "#5516be",
        "primary-container": "#8083ff",
        "on-background": "#e4e1eb",
        "background": "#13131a",
        "outline": "#908fa0",
        "inverse-primary": "#494bd6",
        "surface": "#13131a",
        "secondary-container": "#571bc1",
        "on-primary-fixed": "#07006c",
        "tertiary-container": "#d97721",
        "tertiary-fixed": "#ffdcc5",
        "inverse-on-surface": "#303037",
        "surface-variant": "#34343c",
        "error": "#ffb4ab",
        "surface-container": "#1f1f26",
        "on-tertiary-container": "#452000",
        "on-primary": "#1000a9",
        "primary": "#c0c1ff",
        "on-tertiary-fixed": "#301400",
        "surface-tint": "#c0c1ff",
        "inverse-surface": "#e4e1eb",
        "on-tertiary": "#4f2500",
        "secondary-fixed": "#e9ddff",
        "tertiary-fixed-dim": "#ffb783",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#703700",
        "secondary-fixed-dim": "#d0bcff",
        "secondary": "#d0bcff",
        "surface-container-high": "#2a2931",
        "error-container": "#93000a",
        "on-primary-container": "#0d0096",
        "surface-container-low": "#1b1b22",
        "on-secondary": "#3c0091",
        "surface-bright": "#393840",
        "on-primary-fixed-variant": "#2f2ebe",
        "outline-variant": "#464554",
        "on-surface": "#e4e1eb",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-md": "16px",
        "container-margin-mobile": "16px",
        unit: "4px",
        gutter: "24px",
        "container-margin-desktop": "32px",
        "stack-sm": "8px",
        "stack-lg": "24px",
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "title-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
